export const USER_LOCALSTORAGE_AUTH_KEY = 'USER_LOCALSTORAGE_AUTH_KEY';
export const ARTICLE_VIEW_LOCALSTORAGE_AUTH_KEY = 'ARTICLE_VIEW_LOCALSTORAGE_AUTH_KEY';
export const LOCAL_STORAGE_THEME_KEY = 'theme';
export const LOCAL_STORAGE_LAST_DESIGN_KEY = 'last_design';
